import sharp from 'sharp';
import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
const dirs = ['public/granada', 'public/faculty', 'public/instagram'];

/*
  The tilework runs full-bleed and, in the case of the courses, as a thin
  horizontal slice of an already-cropped band — so a 2400px source lands
  visibly soft on a retina screen once object-cover has scaled it. Those files
  are prepared at their band aspect ahead of time and kept large; everything
  else is a photograph shown whole and 2400px is plenty.
*/
const MAX_WIDTH = { 'public/faculty': 800, 'public/granada': 2400, 'public/instagram': 800 };
const WIDE = { 'zellij-tile-course.jpg': 3840, 'alhambra-arabesque-band.jpg': 3840 };

const out = {};
for (const d of dirs) {
  for (const f of (await readdir(d)).filter(f=>/\.jpe?g$/i.test(f))) {
    const p = path.join(d, f);
    const src = sharp(p);
    const meta = await src.metadata();
    const maxW = WIDE[f] ?? MAX_WIDTH[d];
    const buf = await sharp(p).rotate()
      .resize({ width: Math.min(meta.width, maxW), withoutEnlargement: true })
      .jpeg({ quality: 82, progressive: true, mozjpeg: true }).toBuffer();
    await writeFile(p, buf);
    const m2 = await sharp(buf).metadata();
    const blur = await sharp(buf).resize(16, null, { fit: 'inside' }).jpeg({ quality: 45 }).toBuffer();
    out[`/${d.replace('public/','')}/${f}`] = {
      width: m2.width, height: m2.height,
      blurDataURL: `data:image/jpeg;base64,${blur.toString('base64')}`,
    };
    console.log(`${p}  ${meta.width}x${meta.height} -> ${m2.width}x${m2.height}  ${(buf.length/1024).toFixed(0)}KB`);
  }
}
const ts = `// Generated by scripts/optimize-images.mjs — do not edit by hand.\n// Intrinsic dimensions and blur placeholders for every local image.\nexport const imageMeta = ${JSON.stringify(out, null, 2)} as const;\n\nexport type ImagePath = keyof typeof imageMeta;\n`;
await writeFile('data/image-meta.ts', ts);
console.log('\nwrote data/image-meta.ts');
